modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="nations"
version="${mod_version}"  # Если в оригинале было "1.0.0", замени на это, если используется плейсхолдер
displayName="Nations Mod"
description="Towns, Nations, Claims, Wars"

[[dependencies.nations]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.nations]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.nations]]
modId="dynmap"
mandatory=false
versionRange="[3.7,)"
ordering="NONE"
side="BOTH"
